[package]
name = "rustc_codegen_jvlm"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["dylib"]

[dependencies]

[build-dependencies]
toml = "0.8.23"

[package.metadata.rust-analyzer]
rustc_private = true
